# NUMPY TEST

1. Create a 2 D array and convert it into 6 dimensions array with
the help of dimensions argument?


In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],ndmin=6)
print(a)


[[[[[[ 1  2  3  4  5]
     [ 6  7  8  9 10]]]]]]


2. Create a 4 D array and return any two elements in this array?

In [16]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])


In [22]:
b=a[0]
c=a[1]
print(b)
print(c)

[1 2 3 4]
[5 6 7 8]


3. Create 4 arrays and put it into four dimensions and then return
an array.

In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
d=np.array([10,11,12])
print(a,b,c,d)


[1 2 3] [4 5 6] [7 8 9] [10 11 12]


4. Create an array with the help of arange function, array
elements should be 8 and then return third fourth and fifth
item from this array.


In [7]:
a=np.arange(1,16,2)
b=a[2]
a

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [8]:
a[2],a[3],a[4]

(5, 7, 9)

5. Create two arrays with the help of arange function and
concatenate these arrays, and arrays elements should not be
zero.

In [12]:
a=np.arange(1,6)
b=np.arange(6,11)
c=np.concatenate((a,b))
print(c)


[ 1  2  3  4  5  6  7  8  9 10]


6. x = np. array ([2,1,5,7,0.4,3J])
change this arrays elements into string

In [21]:
x =np.array([2,1,5,7,0,4,3j,'xyz'])
print(x)


['2' '1' '5' '7' '0' '4' '3j' 'xyz']


7. x = np.array([[[[[1,2,3,4,5]]]]]) find the dimensions of this array.

In [24]:
x = np.array([[[[[1,2,3,4,5]]]]]) 
np.ndim(x)

5

8. x = np.array([[[1,2,3,4,5],[6,7,8,9,10]]]) tell me the shape of this
array.

In [25]:
x = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
np.shape(x)

(1, 2, 5)

9. x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) create two
shapes of this 1D array, change it into 2 D array and 3 D array.

In [2]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
y=np.reshape(x,(3,4))
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
y=np.reshape(x,(1,3,4))
y

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [41]:
np.ndim(y)

2

10. Check the size of this array
x = np.array([[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]]])

In [42]:
x = np.array([[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]]])
np.size(x)

15

11. Change the position of this array
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


In [43]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
np.transpose(x)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

12. Create a matrix of 12 take shape as you want, and add 4
with this matrix and then * 3 with this matrix.

In [45]:
x=np.full((4,3),12)
y= x+4
z = y*3
print(z)
print(y)


[[48 48 48]
 [48 48 48]
 [48 48 48]
 [48 48 48]]
[[16 16 16]
 [16 16 16]
 [16 16 16]
 [16 16 16]]


13. Initialize a numpy array with random number return 10
numbers and multiply these numbers with 5.

In [8]:
b=np.random.randint(10,100,(5,2))
c=b*5
c


array([[120, 295],
       [220, 320],
       [100, 185],
       [435, 260],
       [430, 120]])

14. Create a matrix with zeros() and add 10 in this matrix take
5 columns and 6 rows.


In [9]:
x= np.zeros((5,6))
print(x)
y = x+10
print(y)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]]


15. Create a matrix with the ones and dimensions should be
five take 5 rows and 6 columns and perform any two arithmetic
operations as per your choice with this matrix.


In [23]:
a=np.ones((6,5))
b=a*5
c=a+7
print(a)
print(b)
c

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

16. create a mtrix with the help of eye method and do
multiplication with this matrix, to any random number.

In [27]:
a=np.eye(4)
b=a*5
b

array([[5., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 5.]])

17. Create an array with the help of arange function and
reshape this array and create a matrix and then find
the diagonal values, and with the diagonal values do any two
arithmetic calculations.

In [18]:
a=np.arange(1,13,1)
b=np.reshape(a,(4,3))
c=np.diag(b)
add=c+4
mul=c*4
print('The diagonal value : ', c)
print('After adding 4 to diagonal gives this  value : ', add)
print("After multiplying 4 to diagonal gives this value : " , mul)

The diagonal value :  [1 5 9]
After adding 4 to diagonal gives this  value :  [ 5  9 13]
After multiplying 4 to diagonal gives this value :  [ 4 20 36]


 18. Create two arrays and stacking these array column wise
and row wise

In [19]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.column_stack((a,b))
d=np.row_stack((a,b))
print('This stack is column wise : ', c)
print('This stack is row wise : ', d)

This stack is column wise :  [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
This stack is row wise :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


19. Split this 2D array into 3D array
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

In [21]:
x=np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
np.split(a,(4,3))


[array([1, 2, 3, 4]), array([], dtype=int32), array([4, 5])]

20. Find the data type of this array
 x = np. array (["abc",1,5,4.0])

In [23]:
x = np. array (["abc",1,5,4.0])
x.dtype

dtype('<U32')